### PR TITLE
migrate box implementation out of box.h/box.cc

### PR DESCRIPTION
**Pull request by bradh**
The `box.h` and `box.cc` files are pretty large, and box.h is likely to get larger as documentation is added.

This PR is a commit stack migrating various boxes out to codec (or colour) specific implementation.

Diffstat:
```
 CMakeLists.txt |    4 +
 avif.cc        |  190 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 avif.h         |   98 +++++++++++++++++++++++++++++++++
 box.cc         |  853 +-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 box.h          |  363 -----------------------------------------------------------------------------------------------------------------------------
 context.cc     |    1 
 file.cc        |    2 
 file.h         |    3 +
 hevc.cc        |  288 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 hevc.h         |   67 +++++++++++++++++++++++
 jpeg.cc        |   53 ++++++++++++++++++
 jpeg.h         |   52 +++++++++++++++++
 nclx.cc        |  248 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 nclx.h         |  113 ++++++++++++++++++++++++++++++++++++++
 pixelimage.h   |    2 
 vvc.cc         |  128 ++++++++++++++++++++++++++++++++++++++++++++
 vvc.h          |   98 +++++++++++++++++++++++++++++++++
 17 files changed, 1349 insertions(+), 1214 deletions(-)
```

I had hoped for more, but it is a start.

### CODE REVIEW

**Comment by farindk** [comment]
Thanks. Could you please fix the merge conflict. I'll then merge this.

**Comment by bradh** [comment]
Fixed the merge conflict. The failure in emscripten looks unrelated, and appears to have occurred for the last few commits.

**Comment by bradh** [comment]
Resolved additional merge conflict.

**Comment by farindk** [comment]
Thanks for cleaning up. :-)

**Pull request merged**
