### PR TITLE
rgan: initial work on Region Annotation

### PR DESCRIPTION
**Pull request by bradh**
This is initial work on supporting parsing of RegionItem. It is the first substantive change I'm proposing for libheif, and wanted to get feedback before investing too much in the wrong direction.

Region items and region annotations are described in ISO/IEC 23008-12:2022 Section 6.10. AFAICT, it is not present in HEIF 2017 edition.

The current scope I am targeting is parsing and info display. I'm not planning writing at this stage. 

An example of what it might look like in an info display is:

```
MIME type: image/heif
main brand: mif1
compatible brands: mif1, mif2, ns01, unif

image: 1280x720 (id=6007), primary
  color profile: no
  alpha channel: no 
  depth channel: no
metadata:
  none
region annotations:
  id: 6024, reference_width: 1280, reference_height: 720, 2 regions
    Rectangle Region, x: 320, y: 480, width: 320, height: 240
    Point Region, x: 480, y: 600
```

This is a WIP. Remaining tasks include:

  - [ ] Support for polyline
  - [ ] Support for polygon
  - [ ] Support for ellipse
  - [ ] Support for inline mask (at least flagging it is not supported)
  - [ ] Support for mask item

Any additional items and general contribution guidance (e.g. recommended code formatters) would be appreciated.

### CODE REVIEW

**Comment by farindk** [comment]
I would propose to introduce a new object "class" for the region annotation items (`heif_region`). There would be one function to get the list of `heif_region`s from an image and a set of functions working of the regions (e.g., `heif_region_get_geometry`, `heif_region_get_user_description`).

I will make a proposal in a new development branch.

**Comment by farindk** [comment]
I made a proposal for a public API in the regions branch: https://github.com/strukturag/libheif/tree/regions
Please have a look at the `heif.h` file. This is not final. It is open for discussion.

Is it possible to change this PR such that it merges to the 'regions' branch?

**Comment by farindk** [comment]
Do we have any test images for this?

**Comment by bradh** [comment]
Will close this PR, and rework to submit an updated version against the regions branch. 

The only test files are ones that I have made. I uploaded one as part of the set that I provided (look for "rgan" in the file name). If that didn't work, let me know and I'll find another way to get it to you.

**Comment by farindk** [comment]
Ah, ok. Now I found the rgan examples. Thanks.

**Comment by bradh** [comment]
Closing in favour of #816.

**Pull request closed without merging**
