### PR TITLE
Replace low-level file access and HEIF file parsing

### PR DESCRIPTION
**Pull request by farindk**
This is a major rework of how libheif parses input files and handles reading and writing especially large files.
The goal is to
- support reading and writing files that are larger than fits in memory,
- to read/modify/write existing files.

### CODE REVIEW

**Comment by farindk** [comment]
Not finished, but progressed far enough that I decided to merge it into 'master'.

**Comment by kleisauke** [comment]
The libvips fuzzers detected a crash in this implementation that didn't occur on v1.18.2.
```console
$ build-v1.18.2/examples/heif-dec crash-a88cb4551382b7015408ee76bc731e2e99188db6
File contains 2 images
Could not decode image: 0: Invalid input: Unspecified: Corrupt frame detected
$ build-master/examples/heif-dec crash-a88cb4551382b7015408ee76bc731e2e99188db6
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
Aborted (core dumped)
```

Is it too early to report bugs found by fuzzers? I could share the file privately or publicly, whichever you prefer.

**Comment by farindk** [comment]
@kleisauke Would be great if you could share the file. Just attaching it here would be fine I think.

**Comment by kleisauke** [comment]
Great! You can find the file here:
[crash-a88cb4551382b7015408ee76bc731e2e99188db6.zip](https://github.com/user-attachments/files/16737760/crash-a88cb4551382b7015408ee76bc731e2e99188db6.zip) (zipped due to GitHub's upload restrictions)

**Comment by farindk** [comment]
@kleisauke Thanks. The out-of-memory crash should be fixed now.

**Pull request merged**
