### PR TITLE
Heif Properties: Timestamp boxes

### PR DESCRIPTION
**Pull request by dukesook**
Feedback is always appreciated.

### CODE REVIEW

**Comment by farindk** [comment]
Thanks for the PR.
One comment:  since you are merging the master branch into your PR, it makes the PR very hard to read and see what actually changed. Usually, you should keep your PR branch clean with only your changes. That makes it much easier to read, approve, and merge into the master branch without danger to break things there.

Would it be possible that you untangle this PR into a new, clean PR? You could use cherry-picking of your commits to do this.

**Comment by dukesook** [comment]
Okay, I removed the master branch from the PR so my changes are more clear. 

Referring to the API in heif_properties.h: 
Each timestamp parameter shall be interpreted as "unknown" when set to a certain value. I'm trying to hide this detail from the user with a simple nullptr to indicate that the value is "unknown". However, I'm worried that all the pointers overcomplicate the API functions. 

I have an MP4Box.js branch that can read the itai & taic boxes: https://github.com/gpac/mp4box.js/pull/366

**Comment by dukesook** [comment]
I had to git-cherry pick [fix reading images with unspecified jpgC box](https://github.com/strukturag/libheif/commit/8ff82278f98b03a0764fefa31393e4cab29dc675) for the fuzzer to work.

**Comment by farindk** [comment]
At least for `heif_property_get_clock_info`, it may be better to introduce a struct like `heif_tai_clock_info` that collects all fields. This could even be versioned if we want to be able to support future extensions. This eliminates the long list of parameters and pointers.
Then, we could use constants like `heif_tai_clock_correction_offset = 0x7fff...` to make it easier for the user.

**Comment by dukesook** [comment]
resolves #1003

**Pull request merged**
