### PR TITLE
pkg-config: add Requires.private field to allow static builds

### PR DESCRIPTION
**Pull request by lovell**
This ensures the linker is made aware of symbols from transitive dependencies.

### CODE REVIEW

**Comment by lovell** [comment]
It looks like the `libde265 (2)` CI tasks install libde265 to a non-standard location but don't update `PKG_CONFIG_PATH` accordingly, hence the failure of the `go / libde265 (2)` task.

I think the following CI change might get it passing, but unsure if this is the best approach.

```diff
diff --git a/scripts/prepare-ci.sh b/scripts/prepare-ci.sh
index c1a729d..3f9ba15 100755
--- a/scripts/prepare-ci.sh
+++ b/scripts/prepare-ci.sh
@@ -63,6 +63,7 @@ if [ -z "$CHECK_LICENSES" ] && [ -z "$CPPLINT" ] && [ -z "$CMAKE" ]; then
     fi
     if [ ! -z "$GO" ]; then
         CONFIGURE_ARGS="$CONFIGURE_ARGS --prefix=$BUILD_ROOT/dist --disable-gdk-pixbuf"
+        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH $BUILD_ROOT/dist"
     else
         CONFIGURE_ARGS="$CONFIGURE_ARGS --disable-go"
     fi
```

**Comment by lovell** [comment]
(Apologies for the CI noise, I'll hopefully work out the relevant PKG_CONFIG_PATH to modify soon.)

**Comment by farindk** [comment]
Thank you. I resolved the merge conflicts. Please check that your changes are still working. I'll then merge it into master.

**Comment by lovell** [comment]
@farindk LGTM, thank you.

**Comment by farindk** [comment]
Good. Has been merged.

**Pull request merged**
