### PR TITLE
DAM1 update for timestamps

### PR DESCRIPTION
**Pull request by dukesook**
## Sample File
This branch was used to create the following [sample file](https://github.com/dukesook/test-files/blob/master/timestamps/timestamps.heif).

### 'taic' - TAIClockInfoBox
```C++
aligned(8) class TAIClockInfoBox extends FullBox('taic', 0, 0) {
  unsigned int(64) time_uncertainty;
  unsigned int(32) clock_resolution;
  signed int(32) clock_drift_rate;
  unsigned int(2) clock_type;
  unsigned int(6) reserved = 0;
}
```

### 'itai' - TAITimestampBox

```C++
aligned(8) class TAITimestampBox extends ItemFullProperty('itai', 0, 0) {
	TAITimestampPacket timestamp_packet;
}
```

### class TAITimestampPacket

```C++
aligned(8) class TAITimestampPacket {
  unsigned int(64) TAI_timestamp;
  unsigned int(1) synchronization_state;
  unsigned int(1) timestamp_generation_failure;
  unsigned int(1) timestamp_is_modified;
  unsigned int(5) reserved = 0;
}
```

### CODE REVIEW

**Comment by farindk** [comment]
Thank you. Looks good.
Are these changes in the draft expected to be finalized in the July MPEG meeting?

**Comment by dukesook** [comment]
No, it will still take some time before the draft is finalized.

**Comment by farindk** [comment]
> No, it will still take some time before the draft is finalized.

Ok, then we still keep it in the feature branch.

**Comment by farindk** [comment]
I have made some small corrections and rebased the branch on `master`.

**Pull request merged**
