### PR TITLE
Add system-wide installed rav1e support

### PR DESCRIPTION
**Pull request by DarthSim**
This PR adds support of system-wide installed rav1e (can be done with https://github.com/xiph/rav1e#building-the-c-api).
I'm not quite familiar with autoconf/automake, so any comments will be appreciated.

### CODE REVIEW

**Comment by fancycode** [comment]
Please rebase on master and resolve any conflicts. We now also have CI integration that tests if `rav1e` is working correctly.

You can check #341 for a similar PR that changed the `dav1d` detection to support system-wide installations.

**Comment by DarthSim** [comment]
I made the following changes:
- Removed local rav1e support from autotools and cmake configs.
- Updated README with instructions on how to build rav1e with `rav1e.cmd` and use it with libheif. Just like they did for dav1d.
- Updated `rav1e.cmd` to use `cargo-c` instead of `cbindgen` since this is the recommended way to install rav1e.
- Changed cmake configs so it searches rav1e with pkg-config.
- Changed `#include "rav1e/rav1e.h"` to `#include "rav1e.h"` since cargo-c includes `ravie` prefix to the includes path.

**Comment by DarthSim** [comment]
Rebased the branch

**Comment by fancycode** [comment]
lgtm, waiting for @farindk to see if he has something to add

**Comment by farindk** [comment]
Works fine for me with autoconf.
With CMake (3.18) however, I get this error:

````
CMake Warning at cmake/modules/LibFindMacros.cmake:267 (message):
  WARNING: MISSING PACKAGE

  We could not find development headers for RAV1E.  Do you have the necessary
  dev package installed? This package is NOT REQUIRED and you may ignore this
  warning but by doing so you may miss some functionality of libheif.

  Relevant CMake configuration variables:

    RAV1E_INCLUDE_DIR=<not found>
    RAV1E_LIBRARY=<not found>

  You may use CMake GUI, cmake -D or ccmake to modify the values.  Delete
  CMakeCache.txt to discard all values and force full re-detection if
  necessary.

Call Stack (most recent call first):
  cmake/modules/FindRav1e.cmake:17 (libfind_process)
  CMakeLists.txt:67 (find_package)


CMake Warning (dev) at /snap/cmake/619/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (RAV1E) does
  not match the name of the calling package (Rav1e).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindRav1e.cmake:20 (find_package_handle_standard_args)
  CMakeLists.txt:67 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find RAV1E (missing: RAV1E_INCLUDE_DIR RAV1E_LIBRARIES) 
````

Any idea what might be missing? I set PKG_CONFIG_PATH (worked with autoconf), but did not provide any additional options to CMake.

**Comment by DarthSim** [comment]
Just checked twice, works for me well with both system-wide Rav1e and the local one. Please check `pkg-config --libs rav1e` output and ensure that your `PKG_CONFIG_PATH` includes an absolute path to the Rav1e's pkgconfig dir.

**Comment by farindk** [comment]
Right. The path was not absolute...

Great, thanks for the patch.

**Pull request merged**
