### PR TITLE
Change define output_bit_depth

### PR DESCRIPTION
**Pull request by Jamaika1**

### CODE REVIEW

**Review by bradh — COMMENTED** [review]
Or uncompressed, or JPEG 2000, or....

This seems like a bad idea. Potentially the codec could have a default bit depth option.

**Comment by Jamaika1** [comment]
Currently default is 10bit. Adds 8bit tiff/png/jpeg and outputs 10bit with errors.

heifenc_10bit_avx.exe image_24bit.png --verbose -q 100 --vvc -e vvenc --no-alpha --matrix_coefficients=6 --full_range_flag=0 -o image_10bit.vvic
--- construct_pipeline
from: colorspace=RGB chroma=RGB bpp(R)=8 alpha=no
to: colorspace=YCbCr chroma=420 bpp(R)=8 alpha=no matrix-coefficients=6 colour-primaries=1 transfer-characteristics=13 full-range=no <--Why?

image4>heifenc_08bit_avx.exe image_24bit.png --verbose -q 100 --vvc -e vvenc -
-no-alpha --matrix_coefficients=6 --full_range_flag=0 -o image_8bit.vvic
--- construct_pipeline
from: colorspace=RGB chroma=RGB bpp(R)=8 alpha=no
to: colorspace=YCbCr chroma=420 bpp(R)=8 alpha=no matrix-coefficients=6 colour-primaries=1 transfer-characteristics=13 full-range=no <--Why? VVenc doesn't have 8bit output

**Comment by farindk** [comment]
I agree that this change is no good idea, it's changing the default depending on whether some codecs are available even if the user does not use them. Gets us very close to undefined behavior.

However, what we probably need is a way to query the plugins for the supported bit depths and output an error when it is not supported or provide a fallback.

**Comment by Jamaika1** [comment]
> Or uncompressed, or JPEG 2000, or....
> 
> This seems like a bad idea. Potentially the codec could have a default bit depth option.


I don't understand the suggestion but know that codecs will have new features.
Test jpeg2000
heifenc_08bit_avx.exe image_21447_24bit.png --verbose --jpeg2000 -L -q 100 -e openjpeg --no-alpha --matrix_coefficients=6 --full_range_flag=0 -o image_jpeg2000_08.heif
heifenc_08bit_avx.exe image_21447_24bit.png  --verbose --htj2k -L -q 100 -e openjph --no-alpha --matrix_coefficients=6 --full_range_flag=0 -o image_htj2k_08.heif
heifenc_10bit_avx.exe image_21447_48bit.png  --verbose --jpeg2000 -L -q 100 -e openjpeg --no-alpha --matrix_coefficients=6 --full_range_flag=0 -o image_jpeg2000_10.heif
heifenc_10bit_avx.exe image_21447_48bit.png  --verbose --htj2k -L -q 100 -e openjph --no-alpha --matrix_coefficients=6 --full_range_flag=0 -o image_htj2k_10.heif
https://www.sendspace.com/file/n6idh9
Out of curiosity I did a lossless conversion heic jpeg 2000 to jpeg 2000.
For 8bit even jpeg2000 shows something. I would even say correctly.
For 10bit it is not so good.

**Pull request closed without merging**
