### PR TITLE
Bug fix: input class was incorrectly hard coded to nomal

### PR DESCRIPTION
**Pull request by DichenZhang1**

### CODE REVIEW

**Review by DichenZhang1 — COMMENTED** [review]
Bug fix: input class was incorrectly hard coded to nomal

**Comment by DichenZhang1** [comment]
Hi there!

Can someone help to review this pull request?

Thank you!

**Comment by DichenZhang1** [comment]
Friendly ping again,

Can someone help to review this pull request?

Thank you!

**Comment by bradh** [comment]
It looks good to me, but I can't help to get it merged.

**Comment by farindk** [comment]
Thank you and sorry for the delay.

**Pull request merged**
