### PR TITLE
Encode Grid

### LINKED ISSUE #648: Writing Gridded Imagery
I want to write a heif that is gridded. In other words, the image is divided into an arbitrary number of tiles. 

Does libheif support this feature? If not, where would be an ideal place to implement it?

### LINKED ISSUE #1176: How to create a grid HEIF
I saw the code do ImageGrid::write() but I don't know how to use it. I think this is related with Box_iref, iloc and iinf box.
Is there spec or handbook to do this? I have 23008-12 and 14496-12 spec but don't understand how this works..
Could somebody give me some hint?

And is iref_box can reference to single image encoding, not grid?

### PR DESCRIPTION
**Pull request by dukesook**
LIBHEIF_API
struct heif_error heif_context_encode_grid()

Resolves #1176, resolves #648

### CODE REVIEW

**Comment by farindk** [comment]
Thank you. This is nice to have.

In the future, we should have another way to build the grid image step by step by adding tiles one by one, but this is a nice convenience function that can still come in handy.

**Comment by dukesook** [comment]
Great, thanks for merging.

I also wanted a mechanism for encoding grids that are internal to the codec (for example, the uncompressed codec). But I wasn't sure what the best way to do this was.

**Comment by farindk** [comment]
> I also wanted a mechanism for encoding grids that are internal to the codec (for example, the uncompressed codec). But I wasn't sure what the best way to do this was.

Interesting question.
@bradh: Would it be possible to write uncompressed image tiles one by one? Does that pose any problems when the data is `zlib` compressed?

**Comment by bradh** [comment]
It should be possible to write tiles one-by-one. There is a way to say "each of these extents needs to be done separately", and to specify the range.  That opens up the possibility to recycle the bits in one tile that is used to fill many grid spots (e.g. when using a map, and there is a lot of blue ocean; or when making black fill tiles for an image that is rotated to be north-up).

**Pull request merged**
