### PR TITLE
Fix JavaScript rendering for images with odd widths

### LINKED ISSUE #335: online JavaScript decoder shows corrupted image when image width is odd
The decoder https://strukturag.github.io/libheif/ shows a corrupted image when the image width is odd. This is not due to libheif itself, as the image decodes fine even with v1.0.0. I guess it is a problem in the JS canvas drawing code.
See also #331 for a screenshot and the demo image.

### PR DESCRIPTION
**Pull request by fancycode**
Fixes #335 and obsoletes #345.

@catdad can you confirm this fixes the issue?

### CODE REVIEW

**Comment by catdad** [comment]
Overall, the images look correct now, and this is a great improvement.

However, I still see something curious. If I take the resulting image and inspect the bottom closely, I see this (zoomed in in Photoshop):

image
image

While some parts of the bottom line of pixels on the left side are not completely black, they are very very dark. The right side has two rows of missing pixels, and they do appear to be completely black.

I also see this along the right edge:

image

It shows discoloration on the entire right column of pixels.

For reference, here is the entire resulting jpeg:

download

With other converters I have available, like the built-in Windows Photo converter, I do not see these discrepancies.

**Comment by fancycode** [comment]
Thanks for the additional feedback, the missing pixels at the bottom are fixed in https://github.com/strukturag/libheif/pull/369/commits/3a023f9dd1aea629a12bcfe4e518bf53cb88e38f

I already have an idea about the wrong colors on the right side but that needs more changes.

**Comment by fancycode** [comment]
Right side fixed with https://github.com/strukturag/libheif/pull/369/commits/d97b79f3c1657ba1497e9a549a0f0e6bb9547d11

**Comment by catdad** [comment]
Hmm... something about the version at https://github.com/strukturag/libheif/commit/d97b79f3c1657ba1497e9a549a0f0e6bb9547d11 didn't work quite right. Here is the same image:

image

**Comment by fancycode** [comment]
Thanks for testing and providing feedback!

**Pull request merged**
