### PR TITLE
Add uuid property

### PR DESCRIPTION
**Pull request by dukesook**
I'm interested in adding uuid property getters/setters to enable user-defined image metadata.

### CODE REVIEW

**Comment by dukesook** [comment]
I wasn't sure if adding a new Box_uuid class to box.h was a good idea. Instead, I extended the Box class to handle the uuid functionality.

Any feedback would be appreciated.

**Comment by farindk** [comment]
I wouldn't mix this with the base `Box` class, but introduce a catch-all `Box_other` class that keeps the data for everything that libheif does not (yet) understand. I wouldn't even make it uuid specific, but also for other (4cc) boxes that we do not parse yet.

**Comment by farindk** [comment]
I have implemented this in a slightly different way. It is now not limited to 'uuid' boxes anymore, but one can add all sorts of boxes with raw data, and also read the raw data of boxes that are not understood by libheif.

Only caveat at this time: we cannot read the raw data of boxes that were successfully parsed by libheif. This should be added, preferably by storing a pointer to the source data in the Box. But a clean implementation needs more time.

**Comment by farindk** [comment]
@dukesook Please review and if you think that this is ok, I'll close this PR.

**Comment by dukesook** [comment]
This is a great implementation, thanks for doing it. Go ahead and close this PR.

**Pull request closed without merging**
