### PR TITLE
Added missing return value checks that could cause an access violation because the output plane was not allocated.

### PR DESCRIPTION
**Pull request by dlemstra**

### CODE REVIEW

**Review by fancycode — CHANGES_REQUESTED** [review]
Thanks, marked two places where the result should be checked, too.

Also line 2555 is missing a check:
https://github.com/strukturag/libheif/pull/662/files#diff-ae32c56934c4dee29e46c00f3acba5056fb682f16c47a8fc3562962a7dbd42f4R2555

**Comment by dlemstra** [comment]
I have updated the PR to include those two other checks.

**Comment by fancycode** [comment]
This one is still missing (only added as comment in my review):
https://github.com/strukturag/libheif/blob/92c3951eaf6ee543d6733143977886d73fd7bd50/libheif/heif_colorconversion.cc#L2559

**Comment by dlemstra** [comment]
Updated the PR again.

**Review by fancycode — APPROVED** [review]
Thanks, lgtm!

**Comment by fancycode** [comment]
Could you please rebase this on master?

**Comment by dlemstra** [comment]
It looks like some of the tests are failing now. Will take a look at this later today/this weekend. Feel free to give me some pointers on how to fix this.

**Comment by dlemstra** [comment]
Found the mistake that I made. I also made a tiny change the go unit tests while I was investigating this.

**Comment by fancycode** [comment]
> Found the mistake that I made. I also made a tiny change the go unit tests while I was investigating this.

Perfect, thanks. Merging then.

**Pull request merged**
