### PR TITLE
refs #635: second attempt to extend API to disable MT decoding

### PR DESCRIPTION
**Pull request by dk**
I propose here to reuse an existing m_max_decoding_threads, that, if set to 0, effectively reverts to the same effect as if the library was compiled without ENABLE_PARALLEL_TILE_DECODING . That setting is context-dependent and allows both threaded and non-threaded encoding to coexist in a single application.

### CODE REVIEW

**Comment by Edi61** [comment]
Hi dk,

i have review and checked your code, its principially working, but how to change m_max_decoding_threads?
It's a private variable, where you have no influence from outside.

Regards,
Edi61

**Comment by dk** [comment]
Hi Edi61,

I believe heif_context_set_max_decoding_threads was exposed by f0e38af?

/dk

**Comment by Edi61** [comment]
Ah Ok, sorry, overseen it. So it’s fine.

**Comment by farindk** [comment]
Thank you, this looks good.

**Pull request merged**
