### PR TITLE
Regions

### PR DESCRIPTION
**Pull request by bradh**
@farindk This is a port of #802 to the proposed region API. There are some changes from master branch - only the last commit in the sequence is new.

I had to change the API in a few aspects - some are trivial (like signed vs unsigned), but some are more extensive, and possibly not desired.  In particular, I had trouble mapping from the C++ class to the C API without context. That led to this:

```
 LIBHEIF_API
-int heif_region_item_get_number_of_regions(const struct heif_region_item* region_item);
+long unsigned int heif_region_item_get_number_of_regions(const struct heif_image_handle* handle,
+                                                         const struct heif_region_item* region_item);
 
 LIBHEIF_API
-int heif_region_item_get_list_of_regions(const struct heif_region_item* region_item,
-                                         struct heif_region* regions, int max_count);
+long unsigned int heif_region_item_get_list_of_regions(const struct heif_image_handle* handle,
+                                                       const struct heif_region_item* region_item,
+                                                       struct heif_region* regions,
+                                                       long unsigned int max_count);
 
 LIBHEIF_API
 int heif_region_item_get_number_of_annotations(const struct heif_region_item* region_item);
@@ -1768,10 +1783,16 @@ LIBHEIF_API
 enum heif_region_type heif_region_get_type(const struct heif_region* region);
 
 LIBHEIF_API
-struct heif_error heif_region_get_point(const struct heif_region* region, int32_t* x, int32_t* y);
+struct heif_error heif_region_get_point(const struct heif_image_handle* handle,
+                                        const struct heif_region_item* region_item,
+                                        const struct heif_region* region, int32_t* x, int32_t* y);
 
 LIBHEIF_API
-struct heif_error heif_region_get_rectangle(const struct heif_region* region, int32_t* x, int32_t* y, int32_t* width, int32_t* height);
+struct heif_error heif_region_get_rectangle(const struct heif_image_handle* handle,
+                                            const struct heif_region_item* region_item,
+                                            const struct heif_region* region,
+                                            int32_t* x, int32_t* y,
+                                            uint32_t* width, uint32_t* height);
```

That doesn't seem very satisfactory, and will be worse again with the annotations. The alternative would be to have the `heif_region_item` and `heif_region` keep some kind of opaque context, and reinterpret that as a pointer to the parent. I didn't have a sound approach to ensuring it was safe though. 

If you have any improvements, would be grateful for whatever you can offer.

### CODE REVIEW

**Comment by farindk** [comment]
@bradh I thought that `heif_region_item` could be implemented similar to `heif_image_handle` (see in `heif_api_structs.h`).
I can do the change if you want. If I understood you correctly, I just have to cherry-pick 61e0f06 for this, right?
Let me know when I can do this, I want to avoid that we both work on the same code concurrently.

**Comment by bradh** [comment]
I'm currently working on some related parts in my separate (java) implementation, so would appreciate you working on this as you have the time available.

**Comment by farindk** [comment]
I've reworked the regions API. The extra parameters are gone now. I've also changed back the unsigned integers to plain `int`. That may be a matter of taste, but I think that the full range will never be needed and unsigned calls for a lot of problems, like simple for loops counting backwards `while (i>=0)`.

I've also temporarily removed the annotations API because I think that this is easier done in a unified way not differentiating between images and regions (`udes` can be assigned to both).

**Comment by bradh** [comment]
Thanks.

**Pull request closed without merging**
